### ISSUE TITLE
About Contributions

### ISSUE THREAD

**Issue by cyrus01337** [MikeyUsersREC/ERM#4]
Hi,

Seeing some of your code, I could see some parts of it being slightly improved. What are your thoughts on contributions towards the project? Do you have any guidelines, typical tools like auto formatter, expected Python version? These details would help contributing in the future if you are at all interested.

**Comment by NightSlasher35** [comment]
+1 here

**Comment by MikeyUsersREC** [comment]
> Hi,
> 
> Seeing some of your code, I could see some parts of it being slightly improved. What are your thoughts on contributions towards the project? Do you have any guidelines, typical tools like auto formatter, expected Python version? These details would help contributing in the future if you are at all interested.

Hey! Sorry for the late response. It's going to be really easy for contributions in the next update, since I'm going to be separating ERM into different files to improve speed and to generally improve the project. I love contributions towards the project and I believe in open-source projects.

I use Python 3.10 and the packages that are needed to run a development environment are in the .github/workflows/app.yaml file. I use [PyCharm's default auto formatter](https://stackoverflow.com/a/68912246/14820205), which adheres to PEP 8 standards.

I'd be interested in contacting you further if you would like more information on contributions. Thanks for your enquiry!
@NightSlasher35 @cyrus01337

**Comment by MikeyUsersREC** [comment]
@cyrus01337 I have finished the restructuring update. It should be much easier for contributions now. Thanks!
